version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UsersStack"
s3_bucket = "aws-lambda-src"
s3_prefix = "UsersStack"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"


